language: node_js
node_js: node
cache:
  directories:
    - node_modules

before_deploy:
  - npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./
  skip_cleanup: true
  on:
    branch: master
